name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        working-directory: ./frontend
        run: vercel pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_5P6kmsTTVMW1CpIMeIJqug3F
          VERCEL_PROJECT_ID: prj_VAOhR5rlnTA1FWIJH58x1LqVk1H6

      - name: Build
        working-directory: ./frontend
        run: vercel build --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_5P6kmsTTVMW1CpIMeIJqug3F
          VERCEL_PROJECT_ID: prj_VAOhR5rlnTA1FWIJH58x1LqVk1H6

      - name: Deploy to Production
        working-directory: ./frontend
        run: vercel deploy --prebuilt --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_5P6kmsTTVMW1CpIMeIJqug3F
          VERCEL_PROJECT_ID: prj_VAOhR5rlnTA1FWIJH58x1LqVk1H6
